version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://axel:IE98uP_RvVuVsBsOf1zG1Q@punchy-dragon-11093.8nj.cockroachlabs.cloud:26257/clundi?sslmode=verify-full
    ports:
        - "8080:8080"
        - "8443:8443"

    volumes:
      - ./src:/app

  cockroach-db:
    image: cockroachdb/cockroach:v21.1.8
    ports:
      - "26257:26257"
    command: start --insecure
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data

networks:
  default:
