version: '3'
services:
  node-app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    image: flamware/cdocker:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - cockroach-db

  cockroach-db:
    image: cockroachdb/cockroach:v21.1.8
    command: ["start", "--insecure", "--listen-addr=0.0.0.0:26257", "--http-addr=0.0.0.0:8080"]
    ports:
      - "26257:26257"
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
