name: Deploy to VPS

on:
  push:
    branches:
      - V2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:


      - name: SSH into VPS and update clundi_vue
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull flamware/clundi_vue:latest
            docker stop clundi_vue || true
            docker rm clundi_vue || true
            docker run -d -p 8080:80 --name clundi_vue flamware/clundi_vue:latest
            docker pull flamware/clundi_api:latest
            docker stop clundi_api || true
            docker rm clundi_api || true
            docker run -d -p 3000:3000 -p 8445:8445 --name clundi_api flamware/clundi_api:latest
