name: Deploy to VPS

on:
  push:
    branches:
      - V2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t clundi_vue ./src

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag clundi_vue flamware/clundi_vue:latest
          docker push flamware/clundi_vue:latest

      - name: SSH into VPS and update the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull flamware/clundi_vue:latest
            docker stop clundi_vue || true
            docker rm clundi_vue || true
            docker run -d -p 8080:4173 --name clundi_vue_container clundi_vue
