name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: |
          docker build -t flamware/clundi_vue ./client 
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u flamware --password-stdin
          docker tag flamware/clundi_vue:latest flamware/clundi_vue:latest
          docker push flamware/clundi_vue:latest

      - name: SSH into VPS and update the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull flamware/clundi_vue:latest
            docker stop clundi_vue || true
            docker rm clundi_vue || true
            docker run -d -p 8080:4173 --name clundi_vue flamware/clundi_vue:latest
