name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t cdocker .

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull flamware/cdocker:latest


      - name: SSH into VPS and update the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure the SSH key is properly configured
            echo "${{ secrets.SSH_PRIVATE_KEY}}" >> ~/.ssh/authorized_keys
            # Continue with your deployment steps
            docker pull flamware/cdocker:latest
            docker stop cdocker || true
            docker rm cdocker || true
            docker run -d -p 3000:3000 --name cdocker flamware/cdocker:latest