name: Deploy to VPS

on:
  push:
    branches:
      - V2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image for clundi_api
        run: |
          docker build -t flamware/clundi_api ./projet/server
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u flamware --password-stdin
          docker tag flamware/clundi_api:latest flamware/clundi_api:latest
          docker push flamware/clundi_api:latest

      - name: Build and Push Docker image for clundi_vue
        run: |
          docker build -t flamware/clundi_vue ./projet/client 
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u flamware --password-stdin
          docker tag flamware/clundi_vue:latest flamware/clundi_vue:latest
          docker push flamware/clundi_vue:latest

      - name: SSH into VPS and update clundi_vue
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull flamware/clundi_vue:latest
            docker stop clundi_vue || true
            docker rm clundi_vue || true
            docker run -d -p 8080:80 --name clundi_vue flamware/clundi_vue:latest
            docker pull flamware/clundi_api:latest
            docker stop clundi_api || true
            docker rm clundi_api || true
            docker run -d -p 3000:3000 -p 8445:8445 --name clundi_api flamware/clundi_api:latest
